### ISSUE TITLE
When will the source code be released?

### ISSUE THREAD

**Issue by mx8435** [FUZHIYI/TACO#1]

**Comment by FUZHIYI** [comment]
Sorry for delaying to release the code, I will do it in this week.

**Comment by mx8435** [comment]
> Sorry for delaying to release the code, I will do it in this week.

Thanks for your reply. One week has past. :)

**Comment by cklsoft** [comment]
@FUZHIYI  Hoping the source code to reproduce paper results as soon as possible. Thank you very much !
